[project]
name = "tesla-coil-controller"
version = "0.1.0"
description = ""
authors = ["Tim Klein Nijenhuis <tim@hetorus.nl>"]
license = "MIT"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mido>=1.3.3",
    "pyserial>=3.5",
]

[tool.black]
line-length = 120
